@startuml

title https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md

!include participants_ledger1.pu
participant "ilp-connector\n(router)" as router
!include participants_ledger2.pu

!include newLedgerPlugin.pu

!include getInfo.pu

!include getPrefix.pu

!include getAccount.pu

!include sendTransferAndFulfill_2Ledgers.pu

!include sendMessage_2Ledgers.pu

!include rejectIncomingTransfer.pu

!include disconnect.pu

!include isConnected.pu

!include doubts.ipu

@enduml
