@startuml

title https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md

!include participants_ledger1.pu
participant "ilp-connector\n(router)" as router
!include participants_ledger2.pu

!include newLedgerPlugin_seq_diagram.pu

!include getInfo_seq_diagram.pu

!include getPrefix_seq_diagram.pu

!include getAccount_seq_diagram.pu

!include sendTransferAndFulfill_2Ledgers.pu

!include sendMessage_2Ledgers.pu

!include rejectIncomingTransfer.pu

!include disconnect_seq_diagram.pu

!include isConnected_seq_diagram.pu

!include doubts.ipu

@enduml
