InterledgerPaymentRequest
DEFINITIONS
AUTOMATIC TAGS ::=
BEGIN

IMPORTS
    UInt8,
    UInt256
    FROM GenericTypes
;

InterledgerPaymentRequest ::= SEQUENCE {
    -- IPR Version
    version UInt8,
    -- Cryptographic condition
    condition UInt256,
    -- InterledgerProtocolPayment
    packet OCTET STRING
}

END
