LedgerLedgerLotocol
DEFINITIONS
AUTOMATIC TAGS ::=
BEGIN

IMPORTS
    UInt32
    FROM GenericTypes

    InterledgerPacket
    FROM GenericPacket
;

LedgerLedgerLotocolPacket ::= SEQUENCE {
    -- Allow multiple accounts to be multiplexed on one connection
    accountId UInt32,
    -- Used to associate requests and corresponding responses
    -- If requestId = 0, the server MUST not send a response
    requestId UInt32,
    packet InterledgerPacket
}

END
